fixes
PavelKorotchenkov/java-filmorate pull request #8
Opened 2024-02-24 09:21 UTC by PavelKorotchenkov

2024-02-25 22:36 UTC, vlolad requested changes
Привет!

Хорошая работа! Все работает неплохо, но есть пару критичных мест для доработки, связанные с БД: использование ломбока в моделях сейчас опасное, плюс есть лишние запросы в фильмах

Отдельный момент логирование - сейчас почти всё вырезано, надо вернуть хотя бы на уровень контроллера

Тесты хорошие, комментарии понятные)

Жду с доработками!

2024-02-25 22:36 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -@Slf4j
Лучше оставить логирование в контроллере на уровне info или debug, чтобы было видно входящие запросы
В сервисах тоже логирования нет, так что надо на какой-то уровень добавить. Пока логики не так много, можно только в контроллер

2024-02-25 22:36 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +	public Collection<Film> getTopRatedFilms(@RequestParam(defaultValue = "10") int count) {
List более конкретный интерфейс для возвращаемого значения)
Комментарий для всех методов контроллеров/сервисов

2024-02-25 22:36 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +		this.friendshipService = friendshipService;
Неплохое решение сделать отдельный сервис для дружбы!
В целом пока достаточно и просто Storage + запихнуть логику в UserService всю логику обработки дружбы, но данная реализация на уровень выше. Лайк)

2024-02-25 22:36 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  @Data
Те модели, которые взаимодействуют напрямую с БД, лучше не помечать @Data (и некоторыми другими аннотациями из ломбока, которые влияют на хэш-код), так как могут быть большие конфликты с JPA

Решение - заменить на аннотации @Getter и @Setter, ну и аннотации для конструкторов
Подробнее можешь почитать тут: https://thorben-janssen.com/lombok-hibernate-how-to-avoid-common-pitfalls/

2024-02-25 22:36 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>  @Data
Ко всем остальным моделям применим комментарий из класса Film)

2024-02-25 22:36 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/service/LikeService.java
> +	public Collection<Film> showPopular(int count) {
Этот метод больше смотрится в FilmService, т.к. не про лайки, а про выбор фильмов по их отдельному параметру

2024-02-25 22:36 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/service/FriendshipService.java
> +		userStorage.findUserById(friendId); //проверяем, что друг есть в базе
Всё верно!
Ещё неплохая практика - сохранять в переменную то что получаешь и в конце использовать ID из полученных сущностей. Но не обязательно

2024-02-25 22:36 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +		for (Film film : films) {
Сейчас при каждом запросе всех фильмов, на каждый фильм запрашивается отдельным запросом список жанров
Жанры нужно получить в одном запросе, не перебором по фильмам. Это возможно даже в рамках одного запроса. Продумай, как можно доработать!

2024-02-25 22:36 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/storage/mem/InMemoryFilmStorage.java
>  		if (!films.containsKey(filmId)) {
InMemory хранение уже не будет использоваться. Можно для истории оставить, но если мешает - можно удалить)

2024-02-26 07:25 UTC, PavelKorotchenkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -@Slf4j
Основная логика была в DAO классах, поэтому всё внимание было уделено туда) Добавил логи в контроллер и в сервис user.

2024-02-26 11:36 UTC, PavelKorotchenkov commented on src/main/java/ru/yandex/practicum/filmorate/service/LikeService.java
> +	public Collection<Film> showPopular(int count) {
Перенёс

2024-02-26 11:41 UTC, PavelKorotchenkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/mem/InMemoryFilmStorage.java
>  		if (!films.containsKey(filmId)) {
Да, хотел удалить сначала, а потом подумал, что не просто же так нам в лекции писали про @Qualifier) Правда я использую @Primary по итогу, кажется что-то не так работало с квалифаером.

2024-02-26 17:54 UTC, PavelKorotchenkov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  @Data
Спасибо, убрал опасные аннотации)

2024-02-27 18:33 UTC, PavelKorotchenkov commented on src/main/java/ru/yandex/practicum/filmorate/service/FriendshipService.java
> +		userStorage.findUserById(friendId); //проверяем, что друг есть в базе
Поправил

2024-02-28 19:37 UTC, vlolad approved these changes
Огонь, принимаю)

Двигаемся дальше

2024-02-28 19:37 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +				"SELECT f.id, f.name, f.description, f.releaseDate, f.duration, f.mpa_id, mpa.name AS mpa_name, " +
Нехило, молодец)

2024-02-28 19:37 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/storage/mem/InMemoryFilmStorage.java
>  		if (!films.containsKey(filmId)) {
Так тоже допускается, это ок

2024-02-28 20:05 UTC, merged